# Generated by Django 6.0.4 on 2026-04-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='latest_ai_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='latest_ai_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='device',
            name='latest_ai_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
