# Generated by Django 6.0.4 on 2026-04-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_latest_ai_at_device_latest_ai_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='latest_frame',
        ),
        migrations.AddField(
            model_name='device',
            name='latest_frame_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
